[pytest]
testpaths = tests
markers =
    facility_name_min_time_spent: DQ checks for facility_name_min_time_spent_per_visit_date parquet
    facility_type_avg_time_spent: DQ checks for facility_type_avg_time_spent_per_visit_date parquet
    patient_sum_treatment_cost: DQ checks for patient_sum_treatment_cost_per_facility_type parquet
    example: Example/template tests
